# Sinker configurations (for cleanup)
sinker:
  resync_period: 1m
  max_prowjob_age: 4h
  max_pod_age: 4h


# All the Tide configurations
tide:
  queries:
  - orgs:
    - sanster23
  - repos:
    - sangitanalkar/prow-test
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase

deck:
  spyglass:
    size_limit: 500000000
    viewers:
      "started.json|finished.json":
      - "metadata"
      "build-log.txt":
      - "buildlog"
      "artifacts/junit.*\\.xml":
      - "junit"
  tide_update_period: 1s

# Plank configurations
plank:
  # used to link to job results for decorated jobs (with pod utilities)
  #job_url_template: 'http://192.168.99.100:32710/view/gcs/triliok8s/{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if .Spec.Refs}}{{if ne .Spec.Refs.Org ""}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  #job_url_prefix: 'http://192.168.99.100:32710/view/gcs/'
  allow_cancellations: true # AllowCancellations enables aborting presubmit jobs for commits that have been superseded by newer commits in Github pull requests.
  max_concurrency: 50 # Limit of concurrent ProwJobs. Need to be adjusted depending of the cluster size.
  default_decoration_config:
    timeout: 7200000000000
    grace_period: 600000000000
    utility_images:
      clonerefs: "ecos0003:5000/bazel/prow/cmd/clonerefs:image"
      initupload: "ecos0003:5000/bazel/prow/cmd/initupload:image"
      entrypoint: "ecos0003:5000/bazel/prow/cmd/entrypoint:image"
      sidecar: "ecos0003:5000/bazel/prow/cmd/sidecar:image"
